test cases for testCompat.cxx file
resiprocate/resiprocate pull request #4
Opened 2013-11-06 15:39 UTC by shagunshaily

made test cases for
-resipMin
-resipMax
-strncasecmp
-snprintf

2015-07-03 08:43 UTC, muonzoo commented
Anyone object to merging this - it is still clean.

2016-11-18 08:16 UTC, dpocock commented on rutil/test/testCompat.cxx
> +	   assert(resipMax("hello","jello") == "jello");
here you are comparing the pointers and not the strings.  Can you either remove these lines of code that compare strings, or represent the strings using a class such as std::string or resip::Data?

2016-11-18 08:17 UTC, dpocock commented on rutil/test/testCompat.cxx
> +	   assert(resipMin("hello","jello") == "hello");
see earlier comment about comparing pointers with resipMax

2023-03-27 11:55 UTC, mannyad requested changes
Pls

2024-12-10 17:09 UTC, closed without merging